from . import sale_order_conf
from . import cost_sheet
from . import project
from . import project_task
from . import work_order
from . import survey
from . import questionnaire
from . import hr_inherit
from . import product_template
from . import accounting_inherit
from . import res_company
from . import contract
from . import payroll_inherit
