from . import student
from . import course
from . import admission
from . import semester
from . import syllabus
from . import college_class
from . import exam
from . import mark_sheet
from . import promotion
